### ISSUE TITLE
Share steamdeck's controller? 

### ISSUE THREAD

**Issue by djmulder** [FrogTheFrog/moondeck#64] opened 2024-11-17 15:12 UTC
So moonlight will not properly share the controller of the steamdeck. Stuff like gyro is not working. Making moonlight great but not perfect.

Is there a way to add usb sharing like usb/ip or virtualhere to moondeck's startup? And if the game isn't connected anymore, also disconnect the USB? (I think this last one is the hardest)

**Comment by FrogTheFrog** [comment] 2024-11-17 18:18
Moonlight can detect SteamDeck controller, however Steam prevents Moonlight from seeing it in gamemode (it instead exposes it as xbox controller). I tried enabling it, but then it caused weird issues, like double input and so on.

Would usb/ip even work for a SteamDeck controller?

**Comment by djmulder** [comment] 2024-11-17 18:22
Virtualhere works and properly attaches the controller.

I haven't tried usb/ip itself yet, I did get it to install. Need to make the file system not read only to get the package manager to work

**Comment by FrogTheFrog** [comment] 2024-11-17 18:27
You can provide custom Moonlight executable btw, it can also be a script. I'll check if maybe Moonlight no longer gets double input when forcing it to use SteamDeck controller directly.

**Comment by FrogTheFrog** [comment] 2024-11-17 18:54
Still broken.
You can use this script to play around yourself:
```
#!/bin/bash

SDL_GAMECONTROLLER_ALLOW_STEAM_VIRTUAL_GAMEPAD=0 SDL_GAMECONTROLLER_IGNORE_DEVICES="0x28de/0x11ff" /usr/bin/flatpak run com.moonlight_stream.Moonlight "$@"
```

In the logs you'll see that Moonlight is reading SteamDeck controller directly, but it's still broken in gamemode somehow.

Use this to ignore input from it completely. This way you could try to get the usb/ip or virtualhere working:
```
#!/bin/bash

SDL_GAMECONTROLLER_ALLOW_STEAM_VIRTUAL_GAMEPAD=0 SDL_GAMECONTROLLER_IGNORE_DEVICES="0x28de/0x11ff,0x28de/0x1205" /usr/bin/flatpak run com.moonlight_stream.Moonlight "$@"
```

**Comment by djmulder** [comment] 2024-11-18 16:31
Hmm I got this to work fine if in Apollo (fork of Sunshine with virtual displays built in) I set the controller to Playstation.

Could it just be a shear lack of driver/library in Sunshine/Apollo?

**Comment by FrogTheFrog** [comment] 2024-11-18 16:39
> Hmm I got this to work fine if in Apollo (fork of Sunshine with virtual displays built in) I set the controller to Playstation.
> 
> Could it just be a shear lack of driver/library in Sunshine/Apollo?

How does it work fine? What did you do?

**Comment by djmulder** [comment] 2024-11-18 16:49
I added that first script of yours as custom moonlight executable in Apollo I went to: configuration -> input and changed "Emulated Gamepad Type" from Xbox 360 to automatic. Left all the other settings to default:

![Screenshot_20241118-174457](https://github.com/user-attachments/assets/4ecfed9e-5256-41a2-bfec-2510edf07924)

I can use all buttons and gyro. tho dpad and the "open menu" button are mismapped (dpad up seems mapped to "open menu")

**Comment by FrogTheFrog** [comment] 2024-11-18 16:55
Why do I get double input in this case then 🤔? Well, at least it works for you.

**Comment by FrogTheFrog** [comment] 2024-12-08 17:22
Closing as workaround has been provided, but I have no plans to add this to MoonDeck (for now)

**Closed by FrogTheFrog** 2024-12-08 17:22 UTC

**Comment by Icing-weaponry** [comment] 2025-03-01 09:07
> I added that first script of yours as custom moonlight executable and in Apollo I went to: configuration -> input and changed "Emulated Gamepad Type" from Xbox 360 to automatic. Left all the other settings to default:
> 
> ![Screenshot_20241118-174457](https://github.com/user-attachments/assets/4ecfed9e-5256-41a2-bfec-2510edf07924)
> 
> I can use all buttons and gyro. tho dpad and the "open menu" button are mismapped (dpad up seems mapped to "open menu" and open menu to screenshot)

sorry to necro post but I followed this workaround as best I could but I was unable to reproduce. Would you mind assisting me with that? I'd like to have motion working in wild without going desktop/nosteam/moonlight if possible.

I used the first script posted setting it up as an sh as the moonlight custom launch in moondeck.
Installed apollo, setup it up as an automated controller detection as well.
But when I launch mhwild with moondeck the gyro from the steam deck isn't pushed to the game, it does work fine with the desktop workaround though.
Is there a special setting somewhere I'm missing?
