### ISSUE TITLE
Stream opens but game isn't launched

### ISSUE THREAD

**Issue by xxxarmitagexxx** [FrogTheFrog/moondeck#66] opened 2024-11-28 08:23 UTC
Hi,

After installing MoonDeck on Decky and MoonDeckBuddy on the host, pairing them. 
When I attempt to launch a game, the stream will start and I will see my host's desktop but neither the game nor Steam Big Picture will launch.

I have checked that I can launch said game through cmd both directly on the host and while streaming to Desktop/MoonDeckStreaming

Any idea why it is not working.

**Comment by FrogTheFrog** [comment] 2024-11-28 08:27
Give me logs from buddy please.
https://github.com/FrogTheFrog/moondeck/wiki/Buddy-configuration#logging-rules

**Comment by xxxarmitagexxx** [comment] 2024-11-28 08:57
The logs after restarting MoonDeckBuddy and trying to stream a game.
The stream ends after the default timeout. 

[moondeckbuddy.log](https://github.com/user-attachments/files/17945421/moondeckbuddy.log)

**Comment by FrogTheFrog** [comment] 2024-11-28 08:58
Sunshine logs next please

**Comment by FrogTheFrog** [comment] 2024-11-28 09:05
The Sunshine log always says `Executing [Desktop]`. Please triple-check that you have put the everything in correctly:
![sunshine-example](https://github.com/user-attachments/assets/3d84d970-6b4f-488f-8502-3e2698447fcf)

Some people put the executable into Output field instead of Command...

**Comment by xxxarmitagexxx** [comment] 2024-11-28 09:08
Yes I could see this in the logs, however as the stream ends, I have to launch Moonlight to close the host session and the running session is correctly MoonDeckStream. 

![image](https://github.com/user-attachments/assets/55bb2689-1e43-4adc-bc45-62f1765d52f6)

**Comment by xxxarmitagexxx** [comment] 2024-11-28 09:10
no comment, I did exactly what you mentioned

**Comment by FrogTheFrog** [comment] 2024-11-28 09:10
> Some people put the executable into Output field instead of Command...

You are completely disregarding what's in my provided screenshot... Also uncheck the checkbox that my screenshot is pointing to.

**Comment by FrogTheFrog** [comment] 2024-11-28 09:11
Welp, you're too fast...

**Comment by xxxarmitagexxx** [comment] 2024-11-28 09:16
Yes, indeed, now it works. 

I have just the ratio scaling leaves borders, I will have to look into it.

**Comment by xxxarmitagexxx** [comment] 2024-11-28 09:27
Looking at [https://github.com/FrogTheFrog/moondeck-buddy/wiki/Troubleshooting](url)

There is no workaround aside from disabling the pass to Moonlight to get the correct scaling?
As I do indeed use a secondary virtual screen to have correct resolution and HDR through Moonlight.

**Comment by FrogTheFrog** [comment] 2024-11-28 09:31
Sorry, I don't have much time for Q&A anymore. I could recommend using this build for Sunshine:
https://github.com/FrogTheFrog/Sunshine/pull/2

With it disable the MoonDeck option "pass to Buddy" and enable "pass to Moonlight" and Sunshine will perform the resolution changes for real, dummy or virtual displays.

**Comment by xxxarmitagexxx** [comment] 2024-11-29 00:04
Thanks I am trying to build Sunshine from the libdd-part-3 branch but the build fail due to a missing header: 

`fatal error: winrt/Windows.Graphics.Capture.h: No such file or directory
   15 | #include <winrt/Windows.Graphics.Capture.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
`

I am following the build guide on the Sunshine doc: [https://docs.lizardbyte.dev/projects/sunshine/en/latest/building/build.html](url)

after cloning your repository with `git clone https://github.com/FrogTheFrog/sunshine.git --recurse-submodules`

Any pointer would be greatly appreciated as I am not finding much  help googling.

**Comment by FrogTheFrog** [comment] 2024-11-29 11:00
> I have installed the build you recommended and adjusted Moondeck options accordingly but I am still having the scaling issue.
> 
> Anything I need to reconfigure on Sunshine? Targetting a 2560x1600@90 resolution, I have tried with and without Display mode remapping (wildcard and output 2560x1600@90) but am always getting scaling issues.

Please paste the Sunshine logs, just to double check that the resolution was really changed.

**Comment by xxxarmitagexxx** [comment] 2024-11-29 13:06
Here are the Sunshine logs: 
[sunshine.log](https://github.com/user-attachments/files/17959528/sunshine.log)

**Comment by FrogTheFrog** [comment] 2024-11-29 14:28
Hmm, please paste the MoonDeck config from ~/.config/moondeck on SteamDeck

**Comment by xxxarmitagexxx** [comment] 2024-11-29 14:48
Config:
[settings.json](https://github.com/user-attachments/files/17960620/settings.json)

**Comment by FrogTheFrog** [comment] 2024-11-29 15:14
Pfff, can you take a photo of how it looks like?

**Comment by xxxarmitagexxx** [comment] 2024-11-30 10:12
Here are two screenshots: 
- Stream opened through Moondeck:
![moondeck](https://github.com/user-attachments/assets/c2231a7b-d879-4050-9f7b-e4a7e5ddcaec)

- Stream opened through Moonlight/Big Picture:
![moonlight](https://github.com/user-attachments/assets/851bbd14-5dba-45f0-bddb-daab7b443101)

The Moondeck one is not filling the screen.

**Comment by xxxarmitagexxx** [comment] 2024-11-30 21:11
I have tested with setting the app resolution override in Moondeck (under Moonlight settings) with Custom Resolution, Display Resolution, Native, Default. All of the settings yield the same results with the black borders when streaming on the Steam Deck screen through Moondeck. 

What do you mean by my external display potentially not supporting this resolution?
When streaming I can see on my host main screen that the secondary virtual display correctly switch to 2560x1600 and becomes primary:

![image](https://github.com/user-attachments/assets/d81231f8-fa1e-4335-a57d-2b15b9f7bcb5)
![image](https://github.com/user-attachments/assets/96f7924c-eb6a-435e-b231-469cc6af74d1)

It is worth mentioning that if I initiate a stream with 4k@60 through Moondeck and use a dock to display on my TV, the scaling is fine, the image fills the entire TV.

The only issue is with the Steam deck screen.

**Comment by FrogTheFrog** [comment] 2024-12-01 11:00
> What do you mean by my external display potentially not supporting this resolution?

Ignore this. I thought this was happening on external display and not on SteamDeck display.
The issue here is on somewhere SteamDeck side.

FYI, there is no difference between streaming Desktop and MoonDeckStream. Sunshine always streams Desktop first and then starts the application, there is nothing special about the apps.

I have also tested this resolution with my SteamDeck and it works fine :/.

**Comment by FrogTheFrog** [comment] 2024-12-01 11:03
I did manage to reproduce something similar by setting the "maximum game resolution" option in advanced display settings in Steam. Is it set perhaps?

**Comment by xxxarmitagexxx** [comment] 2024-12-01 11:21
Thanks! That was it, I had the Steam maximum game resolution set at 4k as if left as native, I was getting 800p when outputting on my TV through a dock.

After setting this back as native, initiating the stream from Moondeck does fill the screen entirely. 

Thanks again as I would not have thought about it as I was under the impression that this Steam maximum game resolution was only impacting external display when docked.

**Comment by FrogTheFrog** [comment] 2024-12-01 11:34
> Thanks again as I would not have thought about it as I was under the impression that this Steam maximum game resolution was only impacting external display when docked.

Same here... I can't think of a useful use-case where it should be used for internal display...

**Comment by FrogTheFrog** [comment] 2024-12-01 11:34
Closing the issue as everything seems to be resolved.

**Closed by FrogTheFrog** 2024-12-01 11:34 UTC
